Trunk and other fixes
konveyor-ecosystem/kai pull request #187
Opened 2024-05-13 15:01 UTC by jmontleon

I am still seeing an error for `langchain_experimental` in `requirements.txt`. As far as I can tell this issue affects only `<= 0.0.14` and we're on `0.0.35`, even before this PR. 

```
$ cat .trunk/out/6iZ.txt
langchain_experimental 0.0.14 allows an attacker to bypass the CVE-2023-36258 fix and execute arbitrary code via the PALChain in the python exec method. Current version is vulnerable: 0.0.52.
```

https://github.com/advisories/GHSA-gjjr-63x4-v8cq

In the absence of more information, I believe this one is a false positive.

I did not have any issues with `run_demo.py` after this update, but may warrant others testing.

2024-05-22 17:16 UTC, jwmatthews approved these changes
Confirmed ran as expected on MacOS with run_demo and mixtral

`./run_demo.py  3.09s user 4.16s system 1% cpu 10:04.20 total`

2024-05-23 16:12 UTC, JonahSussman requested changes

2024-05-23 16:20 UTC, jmontleon commented on kai/data/misc/incident_store_advanced.md
> -We need to solve the n -> n+1 problem
Thank you, I removed it.

2024-05-23 16:58 UTC, JonahSussman approved these changes
LGTM

2024-05-23 17:11 UTC, merged