Update requirements.txt
konveyor-ecosystem/kai pull request #58
Opened 2024-03-12 13:54 UTC by jwmatthews

Fix #57

2024-03-12 14:14 UTC, savitharaghunathan approved these changes
ACK. Looks like the deps I installed locally

2024-03-12 14:30 UTC, JonahSussman commented
Would strongly reccomend https://github.com/konveyor-ecosystem/kai/pull/62 instead. Will fix https://github.com/konveyor-ecosystem/kai/issues/60

2024-03-12 14:43 UTC, JonahSussman requested changes

2024-03-12 14:43 UTC, JonahSussman commented on requirements.txt
> +sentence-transformers==2.5.1
sentence-transformers must use `2.2.2`

2024-03-13 09:52 UTC, jwmatthews commented
Close in favor of #62

2024-03-13 09:52 UTC, closed without merging